sudo: false
language: java
jdk: oraclejdk10
cache:
  directories:
  - $HOME/.m2
notifications:
  email: false
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify
